services:
  - type: web
    name: bongao-bakery-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://bakerybackend-kpow.onrender.com
